[versions]
#############
# _LIBRARIES #
#############

# compose
compose = "1.4.1"
compose_activity = "1.7.0"
androidxComposeMaterial3 = "1.1.0-beta02"
androidxComposeRuntimeTracing = "1.0.0-alpha03"
androidxComposeBom = "2023.04.00"

# Androidx
kotlin = "1.7.0"
core_ktx = "1.7.0"
lifecycle = "2.3.1"

# Test
junit = "4.13.2"
test_android_junit = "1.1.5"
test_android_espresso = "3.5.1"

###########
# _PLUGINS #
###########
plugin_android = "7.2.1"
plugin_android_kotlin = "1.7.0"

[libraries]

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx"}

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidxComposeMaterial3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

# Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle"}

# Unit test
test-junit = { module = "junit:junit", version.ref = "junit" }

# Android test
test-android-junit = { module = "androidx.test.ext:junit", version.ref = "test_android_junit" }
test-android-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "test_android_espresso" }
test-android-compose-ui = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

[bundles]
# none

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin_android" }
android-library = { id = "com.android.library", version.ref = "plugin_android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin_android_kotlin" }