[versions]
#############
# _LIBRARIES #
#############

# compose
compose = "1.2.0"
compose_activity = "1.3.1"

# Androidx
kotlin = "1.7.0"
core_ktx = "1.7.0"
lifecycle = "2.3.1"

# Test
junit = "4.13.2"
test_android_junit = "1.1.5"
test_android_espresso = "3.5.1"

###########
# _PLUGINS #
###########
plugin_android = "7.2.1"
plugin_android_kotlin = "1.7.0"

[libraries]

# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx"}

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }

# Lifecycle
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle"}

# Unit test
test-junit = { module = "junit:junit", version.ref = "junit" }

# Android test
test-android-junit = { module = "androidx.test.ext:junit", version.ref = "test_android_junit" }
test-android-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "test_android_espresso" }
test-android-compose-ui = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

[bundles]
# none

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin_android" }
android-library = { id = "com.android.library", version.ref = "plugin_android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin_android_kotlin" }